# Generated by Django 5.2.6 on 2025-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0002_crew_route_flight_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
